### ISSUE TITLE
double wikidata entry?

### ISSUE THREAD

**Issue by ralfhauser** [water-fountains/datablue#14]
![grafik](https://user-images.githubusercontent.com/1681677/45796839-df302b80-bca2-11e8-9e6a-e7a5c11a4aa0.png)

https://wikidata.org/wiki/Q27229690  vs. https://wikidata.org/wiki/Q29933540 ?

**Comment by mmmatthew** [comment]
objects have been merged in wikidata. The change will take some time to propagate.
